vich_uploader:
    db_driver: orm

    mappings:
        blogpost_images:
            uri_prefix:         '%app.path.blogpost_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.blogpost_images%'




        #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
